"""RFC 7807 (Problem Details for HTTP APIs) standard error models and factories.

Provides a unified error structure compliant with RFC 7807 while maintaining
backward compatibility with existing client expectations.
"""

from typing import Any

from fastapi.responses import JSONResponse
from pydantic import BaseModel, ConfigDict, Field


class ProblemDetails(BaseModel):
    """RFC 7807 Problem Details representation.

    Specification: https://datatracker.ietf.org/doc/html/rfc7807
    """

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    type: str = Field(
        default="about:blank",
        description="A URI reference that identifies the problem type.",
    )
    title: str = Field(
        description="A short, human-readable summary of the problem type.",
    )
    status: int = Field(
        description="HTTP status code generated by the origin server for this problem.",
    )

    detail: str = Field(
        description="A human-readable explanation specific to this occurrence of the problem.",
    )
    instance: str | None = Field(
        default=None,
        description="A URI reference that identifies the specific occurrence of the problem.",
    )
    code: str | None = Field(
        default=None,
        description="A machine-readable application error code in SCREAMING_SNAKE_CASE.",
    )
    # Backward compatibility extensions
    error: str | None = Field(
        default=None,
        description="Legacy error identifier preserved for client backward compatibility.",
    )
    message: str | None = Field(
        default=None,
        description="Legacy message string preserved for client backward compatibility.",
    )
    incident_id: str | None = Field(
        default=None,
        description="Optional security incident identifier.",
    )


def problem_details_response(
    status_code: int,
    title: str,
    detail: str,
    type_uri: str = "about:blank",
    code: str | None = None,
    error: str | None = None,
    message: str | None = None,
    instance: str | None = None,
    headers: dict[str, str] | None = None,
    **extensions: Any,
) -> JSONResponse:
    """Build a standard RFC 7807 JSONResponse with Content-Type: application/problem+json."""
    content_dict: dict[str, Any] = {
        "type": type_uri,
        "title": title,
        "status": status_code,
        "detail": detail,
    }

    if instance is not None:
        content_dict["instance"] = instance

    if code is not None:
        content_dict["code"] = code

    # Preserve legacy fields for backward compatibility
    content_dict["error"] = error or (code if code else title)
    content_dict["message"] = message or detail

    # Include additional extension members (e.g., violation_type, incident_id, etc.)
    for k, v in extensions.items():
        if v is not None:
            content_dict[k] = v

    response_headers = {"Content-Type": "application/problem+json"}
    if headers:
        response_headers.update(headers)

    return JSONResponse(
        status_code=status_code,
        content=content_dict,
        headers=response_headers,
    )


__all__ = ["ProblemDetails", "problem_details_response"]
