from dataclasses import dataclass
from datetime import UTC, datetime
from uuid import UUID, uuid4

from src.domain.conversations.events.conversation_created import ConversationCreatedDomainEvent
from src.domain.shared.aggregate_root import AggregateRoot
from src.domain.shared.domain_error import DomainError


@dataclass(eq=False)
class Conversation(AggregateRoot):
    """Aggregate root for a conversation.

    The domain does not know whether messages will later be generated by
    OpenAI, Azure OpenAI, Anthropic, a local model, or another provider.
    """

    id: UUID
    title: str
    created_at: datetime

    def __post_init__(self):
        super().__init__()

    @classmethod
    def create(cls, title: str) -> "Conversation":
        normalized = title.strip()
        if not normalized:
            raise DomainError("Conversation title cannot be empty.")
        if len(normalized) > 200:
            raise DomainError("Conversation title cannot exceed 200 characters.")

        instance = cls(
            id=uuid4(),
            title=normalized,
            created_at=datetime.now(UTC),
        )
        instance.record_event(ConversationCreatedDomainEvent(conversation_id=instance.id))
        return instance
