"""ToolCall Value Object."""

from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any


@dataclass(frozen=True)
class ToolCall:
    """Immutable representation of a tool execution intention generated by an LLM."""

    call_id: str
    tool_name: str
    arguments: dict[str, Any]
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def __post_init__(self) -> None:
        if not self.call_id or not self.call_id.strip():
            raise ValueError("El call_id no puede estar vacío.")
        if not self.tool_name or not self.tool_name.strip():
            raise ValueError("El tool_name no puede estar vacío.")
        if not isinstance(self.arguments, dict):
            raise ValueError("Los argumentos deben ser un diccionario.")
